#!/usr/bin/env bash
set -x

input_iso="${1}"
[[ -n ${input_iso} ]] || exit 1
extracted=$(mktemp -d -p $PWD)

extract() {
  cat ${input_iso} | bsdtar -C ${extracted} -xf - && chmod -R +w ${extracted}
}

do_stuff() {
  cd ${extracted} || exit 1
  rm -rf {css,doc,pics,README.*,*.i*,setup.exe} \
         isolinux/{*.txt,*.cfg}
  cat<< EOL >>isolinux/isolinux.cfg
path

menu hshift 7
menu width 61

menu title PART DEBIAN

menu background splash.png
menu color title	* #FFFFFFFF *
menu color border	* #00000000 #00000000 none
menu color sel		* #ffffffff #76a1d0ff *
menu color hotsel	1;7;37;40 #ffffffff #76a1d0ff *
menu color tabmsg	* #ffffffff #00000000 *
menu color help		37;40 #ffdddd00 #00000000 none
menu vshift 8
menu rows 12
menu helpmsgrow 14
menu cmdlinerow 16
menu timeoutrow 16
menu tabmsgrow 18

label install
  menu label ^Install
  kernel /install.amd/vmlinuz
  append vga=788 initrd=/install.amd/initrd.gz file=/cdrom/preseed.cfg debian-installer=en_US.UTF-8 locale=en_US.UTF-8 kbd-chooser/method=us keyboard-configuration/xkb-keymap=us fb=false debconf/frontend=noninteractive console-setup/ask_detect=false console-keymaps-at/keymap=us

default vesamenu.c32
timeout 20
EOL

  cat<< EOL >>preseed.cfg
d-i debian-installer/language string en
d-i debian-installer/country string IR
d-i debian-installer/locale string en_GB.UTF-8
d-i console-keymaps-at/keymap select us
d-i base-installer/kernel/override-image string linux-server
d-i clock-setup/utc boolean true
d-i clock-setup/utc-auto boolean true
d-i keymap select us
d-i partman-auto/disk string
d-i partman-auto/method string regular
d-i partman-auto/choose_recipe select atomic
d-i partman-partitioning/confirm_write_new_label boolean true
d-i partman/choose_partition select finish
d-i partman/confirm boolean true
d-i partman/confirm_nooverwrite boolean true
d-i partman/confirm_write_new_label boolean true
#d-i netcfg/enable boolean false
d-i netcfg/get_hostname string part
d-i netcfg/get_domain string debian
d-i mirror/country string manual
d-i mirror/http/hostname string debian.asis.ai
d-i mirror/http/directory string /debian
d-i mirror/http/proxy string
d-i pkgsel/include string openssh-server sudo
d-i pkgsel/install-language-support boolean false
d-i pkgsel/update-policy select none
d-i pkgsel/upgrade select none
d-i time/zone string Asia/Tehran
d-i passwd/root-login boolean false
d-i passwd/username string part
d-i passwd/user-fullname string part
d-i passwd/user-password password part
d-i passwd/user-password-again password part
d-i user-setup/allow-password-weak boolean true
d-i user-setup/encrypt-home boolean false
d-i preseed/late_command string sed -i '/^deb cdrom:/s/^/#/' /target/etc/apt/sources.list
apt-cdrom-setup apt-setup/cdrom/set-first boolean false
popularity-contest popularity-contest/participate boolean false
tasksel tasksel/first multiselect standard
d-i grub-installer/only_debian boolean true
d-i grub-installer/with_other_os boolean true
d-i grub-installer/bootdev  string default
d-i finish-install/reboot_in_progress note
d-i preseed/late_command string apt-install git grc htop less mtr-tiny screen vim xtail
EOL
}

repack() {
  genisoimage -r -J -no-emul-boot -boot-load-size 4 -boot-info-table \
              -b isolinux/isolinux.bin \
              -c isolinux/boot.cat \
              -o ../part-debian.iso ${extracted}
}

clean() {
  rm -rf ${extracted}
}

extract
do_stuff
repack
clean
