#!/usr/bin/env bash

loop="/dev/loop0"
disk_image="${1}"
target="${2}"

provision="
  locale-gen;
  echo ${disk_image} >/etc/hostname;
  passwd;
  DEBIAN_FRONTEND=noninteractive \
  apt-get -qq --no-install-recommends install grub-pc >/dev/null&&
  grub-install --target=i386-pc --boot-directory=/boot/ ${loop}&&
  sed -i '/GRUB_TIMEOUT/s/5/0/g' /etc/default/grub&&
  sed -i 's/quiet/console=ttyS0/g' /etc/default/grub&&
  update-grub
"

mountp="$(mktemp -d -p .)" || exit 1
losetup ${loop} ${disk_image} || exit 1
mount ${loop}p2 ${mountp} && echo 'mount done'
cp -a "${target}"/* "${mountp}"/ && echo 'copy done'
for i in {dev,proc,sys}; do mount --bind /${i} "${mountp}"/$i; done
ln -s /proc/mounts "${mountp}"/etc/mtab

uuid=$(blkid -o value -s UUID ${loop}p2)
echo -e "UUID=${uuid} /\text4 errors=remount-ro\t0 1" >"${mountp}"/etc/fstab
sed -i '/# en_US.UTF-8/s/^#//g' "${mountp}"/etc/locale.gen
echo 'LANG="en_US.UTF-8"' >"${mountp}"/etc/default/locale
echo "${provision}" >"${mountp}"/prov
chroot "${mountp}" /bin/sh -c 'chmod +x /prov && /prov && rm -f /prov'

sync
for i in {dev,proc,sys}; do umount "${mountp}"/$i; done
umount ${mountp} && rmdir ${mountp} && losetup -d ${loop} && echo 'all clean'
